name: Build

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        # 3.9 has issue with intelhex https://github.com/python-intelhex/intelhex/issues/45
        python-version: '3.8'

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      
    - name: Checkout Code
      uses: actions/checkout@v1
      with:
        submodules: true      
        
    - name: Install Toolchains
      run: |
        pip3 install adafruit-nrfutil uritemplate requests intelhex
        npm install --global xpm
        # 9.3.1-1.2.1 is xpack modified version which significantly increased compiled size to 6-7KB and cause flash overflow.
        # Skip this version for now, we will try again with next official release from ARM
        xpm install --global @xpack-dev-tools/arm-none-eabi-gcc@9.3.1-1.1.1
        echo "::add-path::`echo $HOME/opt/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/*/.content/bin`"
    
    - name: Build
      run: python3 tools/build_all.py
      
    - name: Upload Release Asset
      if: github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'rerequested')
      working-directory: tools
      env:
        UPLOAD_URL: ${{ github.event.release.upload_url }}
        ADABOT_GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: "[ -z \"$ADABOT_GITHUB_ACCESS_TOKEN\" ] || python3 -u upload_release_files.py"
      
